#!/bin/bash
 
set -e

PROJECT=jsonlikeql
EXT=jql
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EXEC=$DIR/makefile-unix/$PROJECT

LOGFILE=build.log
LOGGALGAS=galgas.log

MAKEFILEUNIX=1

COMPILARGS=--max-errors=1 #--max-warnings=0

export PATH=$PATH:$DIR

rm -f $LOGFILE
galgas  +${PROJECT}.galgasProject $COMPILARGS --emit-syntax-diagrams --output-html-grammar-file #> $LOGFILE

if [ -f $EXEC ]; then
	echo -e "Deleting old executable ..."
	rm -f $EXEC*
	echo -e "Done !" 
fi

./makefile-unix/build.py

#run after compiling to accelerate the development
if [[ MAKEFILEUNIX -eq 1 && -f ./makefile-unix/$PROJECT ]]; then 
	echo -e "Starting tests ... "
	
	# deleting old jql files
	rm -rf $DIR/files/*.sql

	for file in $DIR/files/*.jql 
	do  
		if [[ -f $file ]]; then 
			echo "Testing file " $file " ..."
			./makefile-unix/$PROJECT $COMPILARGS $file 
			if [[ $? -gt 0 || $? -lt 0 ]];	then
				exit 1
			fi
			echo -e "Done !"
		fi
	done
	echo -e "All tests passed !! "
fi
