/*
* Query
* SQL queries generated by Query with Galgas
* Author : Blixit
*/
/* Requete test*/
SELECT FROM `fakeTable` VALUES ... ;;
/* Requete aire*/
SELECT FROM `fakeTable` VALUES ... ;;
/* Requete ajouterUser*/
INSERT INTO `fakeTable` VALUES (...) ;
/* Requete funct*/
INSERT INTO `fakeTable` VALUES (...) ;
/* Requete tes*/
DELETE FROM `fakeTable` WHERE name = 'yes'  ;
/* Requete tes*/
DELETE FROM `fakeTable` ;
/* Requete lm*/
UPDATE `fakeTable` SET ... ;
