/*
* Query
* SQL queries generated by Query with Galgas
* Author : Blixit
*/
/* Requete SELECT `test` */
SELECT FROM `fakeTable` VALUES ... ;;
/* Requete SELECT `aire` */
SELECT FROM `fakeTable` VALUES ... ;;
/* Requete MUTATE `ajouterUser` */
INSERT INTO `fakeTable` VALUES (...) ;
/* Requete MUTATE `funct` */
INSERT INTO `fakeTable` VALUES (...) ;
/* Requete DELETE `tes` */
DELETE FROM `tes` WHERE name = 'yes'  ;
/* Requete DELETE `test` */
DELETE FROM `Montype` WHERE  ;
/* Requete MUTATE `lm` */
UPDATE `fakeTable` SET ... ;
